server:
  port: 10000 # 服务端口
spring:
  application:
    name: config-server # 指定服务名
  cloud:
    config: # config 相关配置
      server:
        git:
          uri: https://gitee.com/moonzero/springcloud-config-sample-repo.git # 指定配置文件所在服务的地址（可以是本地存储）