spring:
  rabbitmq:
    addresses: 192.168.12.132
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output: # Spring Cloud Stream 内置的发送消息的通道（名称为output）
          destination: stream-sample-default  # 指定消息发送的目的地。在 RabbitMQ 中，会发送到一个stream-sample-default的exchange中
          contentType: text/plain # 用于指定消息的类型
        customOutput: # 自定义的发送消息的通道（在CustomProcessor接口中定义的）
          destination: stream-sample-custom
          producer:
            partitionKeyExpression: payload # 指定分区键（关键字）的表达式规则。可以使用SpEL表达式配置。注：属性名也可以使用中划线间隔方式，如，partition-key-expression
            partitionCount: 2 # 指定消息分区的数量
      binders: # 配置绑定器
        defaultRabbit:
          type: rabbit # 指定绑定消息中间件的类型