### 新增商品
POST http://localhost:9001/product
Content-Type: application/json

{
  "productName": "石原里美手办",
  "status": 1,
  "price": 2220,
  "productDesc": "呵呵！"
}

### 查询所有商品
GET http://localhost:9001/product
Accept: application/json

###