server:
  port: 8080
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
logging:
  level:
    com.moon.example.feign: debug # 设置 Feign client 接口 package 日志级别为 debug
    org.apache.http.wire: debug  # 开启 HttpClient 相关接口的日志
    org.apache.http.headers: debug
    okhttp3: debug # 开启 OkHttp 相关接口的日志
feign:
  client:
    config:
      # service-provider: # 局部配置需要调用的服务名称
      default: # 全局配置需要调用的服务名称
        loggerLevel: FULL  # 配置 Feign 的日志级别，相当于代码配置方式中的Logger
  httpclient:
    enabled: false # 开启 httpclient
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路由的最大连接数
  okhttp:
    enabled: true # 开启 okhttp